## 带等式约束的优化问题

### 给定风险，求解风险最小的组合权重

**符号**

收益的期望值
$$ \vec{\mu} = \left( \begin{matrix} \mu _1 \\ \vdots \\ \mu _i \\ \vdots \\ \mu _n \\ \end{matrix} \right) $$

收益的协方差矩阵
$$
\vec{\Sigma} = \left(
\begin{matrix}
\sigma_1^2 & \rho_{12} \sigma_1 \sigma_2 & \cdots & \rho_{1n} \sigma_1 \sigma_n \\
\rho_{21} \sigma_2 \sigma_1 & \sigma_2^2 & \cdots & \rho_{2n} \sigma_2 \sigma_n \\
\vdots & \vdots & \ddots & \vdots \\
\rho_{n1} \sigma_2 \sigma_n & \rho_{n2} \sigma_n \sigma_2 & \cdots & \sigma_n^2 \\
\end{matrix}
\right)
$$

资产权重
$$ \vec{w} = \left( \begin{matrix} w _1 \\ \vdots \\ w _i \\ \vdots \\ w _n \\ \end{matrix} \right) $$

组合收益的期望值 $\mu_\pi = \vec{\mu} ^ T \vec{w}$

组合收益的方差 $\sigma_\pi ^2 = \vec{w}^T \vec{\Sigma} \vec{w}$


**分解协方差矩阵**

标准差向量
$$ \vec{\sigma} = \left( \begin{matrix} \sigma _1 \\ \vdots \\ \sigma _i \\ \vdots \\ \sigma _n \\ \end{matrix} \right) $$

标准差对角阵

$$
\vec{S} = \vec{D}(\sigma) = \left(
\begin{matrix}
\sigma_1 & 0 & \cdots & 0 \\
0 & \sigma_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \sigma_n \\
\end{matrix}
\right)
$$

相关性矩阵
$$
\vec{R} = \left(
\begin{matrix}
1 & \rho_{12} & \cdots & \rho_{1n} \\
\rho_{21} & 1 & \cdots & \rho_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
\rho_{n1} & \rho_{n2} & \cdots & 1 \\
\end{matrix}
\right)
$$

协方差矩阵
$$
\vec{\Sigma} = \vec{SRS} = \left(
\begin{matrix}
\sigma_1^2 & \rho_{12} \sigma_1 \sigma_2 & \cdots & \rho_{1n} \sigma_1 \sigma_n \\
\rho_{21} \sigma_2 \sigma_1 & \sigma_2^2 & \cdots & \rho_{2n} \sigma_2 \sigma_n \\
\vdots & \vdots & \ddots & \vdots \\
\rho_{n1} \sigma_2 \sigma_n & \rho_{n2} \sigma_n \sigma_2 & \cdots & \sigma_n^2 \\
\end{matrix}
\right)
$$

**拉格朗日方法**

等式的优化问题的一般形式如下：

$$\begin{aligned}
\min_{x_1, \cdots, x_n} f(x_1,\cdots, x_n)
\end{aligned}$$

subject to :

$$\begin{aligned}
& g_1(x_1,\cdots, x_n) & = & \ b_1 \\
& & \vdots \\
& g_m(x_1,\cdots, x_n) & = & \ b_m \\
\end{aligned}$$

使用拉格朗日方法构造无约束条件的优化形式：

$$L(\vec{x}, \vec{\lambda}) = f(\vec{x}) + \sum_{j=1}^{m} \lambda_j (g_j(\vec{x})-b_j)$$


**要求解的问题**：在给定回报的情况下，最小化组合风险

目标函数$\begin{aligned} \min_{\vec{w}} = \frac{1}{2} \sigma_{\pi}^2 = \frac{1}{2} \vec{w}^T \vec{\Sigma} \vec{w} \end{aligned}$

约束条件
- 目标收益：$\mu_{\pi} = \vec{\mu}^T \vec{w} = \vec{w}^T \vec{\mu} = m$
- 权重和为1：$\vec{1}^T \vec{w} = \vec{w}^T \vec{1} = 1$

使用拉格朗日方法构造无约束条件的优化问题：
$$
L(\vec{w}, \lambda, \gamma) = \frac{1}{2} \vec{w}^T \vec{\Sigma} \vec{w} + \lambda(m - \vec{w}^T \mu) + \gamma(1 - \vec{w}^T \vec{1})
$$

求解得到$\vec{w}^* = \vec{\Sigma}^{-1} (\lambda \vec{\mu} + \gamma \vec{1})$，其中，

$\left\{\begin{aligned}
\lambda &= \frac{Am-B}{AC-B^2} \\
\gamma &= \frac{C-Bm}{AC-B^2} \\
\end{aligned}\right.$

$\left\{\begin{aligned}
A &= \vec{1}^T \vec{\Sigma}^{-1} \vec{1} \\
B &= \vec{1}^T \vec{\Sigma}^{-1} \vec{\mu} = \vec{\mu}^T \vec{\Sigma}^{-1} \vec{1} \\
C &= \vec{\mu}^T \vec{\Sigma}^{-1} \vec{\mu} \\
\end{aligned}\right.$

In [1]:
import numpy as np

# 单位向量
unit = np.array([1.0, 1.0, 1.0, 1.0, ]).reshape(4, 1)

# 收益均值
u = np.array([0.05, 0.07, 0.15, 0.27, ]).reshape(4, 1)
# 收益方差
s = np.array([0.07, 0.12, 0.30, 0.60, ]).reshape(4, 1)
# 相关性矩阵
R = np.array([[1, 0.8, 0.5, 0.4, ],
             [0.8, 1, 0.7, 0.5, ],
             [0.5, 0.7, 1, 0.8, ],
             [0.4, 0.5, 0.8, 1, ], ])


In [2]:
# 目标收益
m = 0.1

print('====================')
print('params')
print()
print('mean of returns :')
print(u)
print()
print('standard deviation of returs :')
print(s)
print()
print('correlation matrix :')
print(R)
print()
print('target retusn :')
print(m)
print()
print('====================')

# 向量变为对角阵
S = np.diag(s.reshape(4))
# 协方差矩阵
Cov = np.matmul(np.matmul(S, R), S)
# 协方差矩阵的逆矩阵
Cov = np.matrix(Cov)
Cov_reverse = Cov.I

# 三个中间变量
A = np.matmul(np.matmul(unit.T, Cov_reverse), unit).item(0, 0)
B = np.matmul(np.matmul(u.T, Cov_reverse), unit).item(0, 0)
C = np.matmul(np.matmul(u.T, Cov_reverse), u).item(0, 0)

# 拉格朗日系数
lam = (A * m - B) / (A * C - B * B)
gam = (C - B * m) / (A * C - B * B)

# 权重w
w = np.matmul(Cov_reverse, lam * u + gam * unit)

print('++++++++++++++++++++')
print('standard deviation matrix')
print(S)
print()
print('covariance matrix')
print(Cov)
print()
print('inverse of covariance matrix')
print(Cov_reverse)
print()
print('A={}, B={}, C={}'.format(A, B, C))
print()
print('lambda={}, gamma={}'.format(lam, gam))
print()
print('weights')
print(w)
print()
print('++++++++++++++++++++')

params

mean of returns :
[[0.05]
 [0.07]
 [0.15]
 [0.27]]

standard deviation of returs :
[[0.07]
 [0.12]
 [0.3 ]
 [0.6 ]]

correlation matrix :
[[1.  0.8 0.5 0.4]
 [0.8 1.  0.7 0.5]
 [0.5 0.7 1.  0.8]
 [0.4 0.5 0.8 1. ]]

target retusn :
0.1

++++++++++++++++++++
standard deviation matrix
[[0.07 0.   0.   0.  ]
 [0.   0.12 0.   0.  ]
 [0.   0.   0.3  0.  ]
 [0.   0.   0.   0.6 ]]

covariance matrix
[[0.0049  0.00672 0.0105  0.0168 ]
 [0.00672 0.0144  0.0252  0.036  ]
 [0.0105  0.0252  0.09    0.144  ]
 [0.0168  0.036   0.144   0.36   ]]

inverse of covariance matrix
[[ 591.54096421 -310.55900621   34.50655625  -10.35196687]
 [-310.55900621  301.93236715  -64.41223833   10.06441224]
 [  34.50655625  -64.41223833   48.30917874  -14.49275362]
 [ -10.35196687   10.06441224  -14.49275362    8.05152979]]

A=239.3440467974628, B=9.6184560780834, C=0.5502809819580001

lambda=0.365279369427286, gamma=-0.010501299717695733

weights
[[0.52841211]
 [0.17288808]
 [0.15976434]
 [0.13893547]]

++++

### 最小方差组合

去掉约束条件1，即不给定期望收益

求解得到

最小方差组合的收益$m_g = \frac{B}{A}$

权重 $\begin{aligned} w_g = \frac{\vec{\Sigma}^{-1} \vec{1}}{A} \end{aligned}$

方差 $\begin{aligned} \sigma_g^2 = \frac{1}{A} \end{aligned}$

In [3]:
wg = np.matmul(Cov_reverse, unit) / A
mg = B/A
sg = np.sqrt(1/A)

print('weights')
print(wg)
print()

print('return')
print(mg)
print()

print('standard deviation')
print(sg)
print()


weights
[[ 1.27488672]
 [-0.26311273]
 [ 0.01633942]
 [-0.02811341]]

return
0.04018673623506796

standard deviation
0.06463811533136278



### 切线组合

优化问题变为：

目标函数$\begin{aligned} \min_{\vec{w}} = \frac{1}{2} \sigma_{\pi}^2 = \frac{1}{2} \vec{w}^T \vec{\Sigma} \vec{w} \end{aligned}$

约束条件
- $r + \vec{w}^T (\vec{\mu} - r \vec{1})= m$

求解得到 $$\vec{w}^* = \lambda \vec{\Sigma}^{-1}(\vec{\mu} - r \vec{1})$$

带入约束条件可求解出$$\lambda = \frac{m -r}{(\vec{\mu} - r \vec{1})^T \vec{\Sigma}^{-1} (\vec{\mu} - r \vec{1}) } $$, 

代入得到最终的 $$\vec{w}^* = \frac{ (m - r) \vec{\Sigma}^{-1} (\vec{\mu} - r \vec{1}) }{ (\vec{\mu} - r \vec{1})^T \vec{\Sigma}^{-1} (\vec{\mu} - r \vec{1}) }$$

In [4]:
r = 0.025
m = 0.1

t = u - r * unit

w = (m - r) * np.matmul(Cov_reverse, t) / np.matmul(np.matmul(t.T, Cov_reverse), t)

print(r)
print(m)
print(w)
print(1 - np.matmul(w.T, unit))

0.025
0.1
[[0.88735248]
 [0.08126325]
 [0.15484343]
 [0.12164862]]
[[-0.24510779]]


切线组合全部投资在风险资产上$$\vec{w_t} = \frac{\vec{\Sigma}^{-1}(\vec{\mu} - r \vec{1})}{B-Ar}$$

均值 $$m_t = \vec{w_t}^T = \frac{C-Br}{B-Ar}$$

方差 $$\sigma_t = \vec{w_t}^T \vec{\Sigma} \vec{w_t} = \frac{C-2rB +r^2 A}{(B-Ar)^2}$$

In [5]:
wt = np.matmul(Cov_reverse, u - r * unit) / (B - A * r)
mt = (C - B * r) / (B - A * r)
st = np.sqrt((C - 2 * B * r + A * r * r) / ((B - A * r) ** 2))
wt, mt, st

(matrix([[0.71267122],
         [0.06526604],
         [0.12436147],
         [0.09770128]]), 0.08523574883594777, 0.12873114050310236)

## Black-Litterman模型

动态资产选择模型，关注超额收益

超额收益$$\tilde{R} = R - r \vec{1}, \quad \tilde{R} \sim N(\tilde{\mu}, \Sigma) $$

其中$\tilde{\mu} = \vec{\mu} - r \vec{1}$, $\Sigma$是协方差矩阵

Black-Litterman模型认为：真实的超额回报均值$\tilde{\mu}$无法直接计算或观测到，因此依赖于估计量$\pi$
$$\pi \sim N(\tilde{\mu}, \Sigma_{\pi})$$

$\pi$是围绕$\tilde{\mu}$波动的噪声项（随机项）
$$\pi = \tilde{\mu} + \epsilon , \quad \epsilon \sim N(0, \Sigma_{\pi})$$

假设$\epsilon$与$\tilde{\mu}$不相关，则
$$\tilde{R} \sim N(\tilde{\mu}, \Sigma_r) , \quad \Sigma_r = \Sigma + \Sigma_{\pi}$$

Black-Litterman公式有两种推导方法：
- Theil's mixed estimation model：使用generalised least squares regression (GLS)方法，GLS是OLS的扩展
- Bayes's Formula：用获得的新信息优化资产配置，可以用贝叶斯统计方法解释（贝叶斯公式用新条件更新先验概率，得到后验概率）

**贝叶斯方法的内容：**
- Step 0: Introducing Bayes' Formula;
- Step 1: Reverse optimization to get the prior;
- Step 2: Inputing the view;
- Step 3: Combining to get the posterior distribution;
- Step 4: Asset allocation.

**Step 0: Introducing Bayes' Formula**

$$P(E|I) = \frac{P(I|E)}{P(I)} \times P(E)$$

其中:
- $E$是事件
- $I$是新信息
- $P(E)$是先验概率，没有信息$I$之前的概率
- $P(E|I)$是后验概率，知道信息$I$之后的概率（主观概率）
- $P(I)$是归一化常量

**Step 1: Reverse optimization to get the prior**

可能的先验条件：

- 平均分配（每个资产$1/N$）
- 全局最小方差组合
- any other `neutral and uninformed' portfolio

这些选择都不理想：

- 得到全局最小方差，隐含了要估计超额收益。如果使用历史收益，可能不能反映未来期望，导致不切实际的组合
- 平均分配不能建立超额回报的先验视角（用均价分配表示什么都没有知道，没有先验知识）

Black-Litterman使用equilibrium CAPM portfolio也就是求解：
$$ \max_{\vec{w}} \vec{w}^T \tilde{R} - \frac{\lambda}{2} \vec{w}^T \Sigma \vec{w}$$

$\Sigma$是超额回报的协方差矩阵

求解得到$$ \vec{w}^{*} = \frac{1}{\lambda} \Sigma^{-1} \tilde{R}$$

现在的问题：不知道超额回报向量

对于市场组合有(<font color='red'>这里的意思似乎是用市场组合的超额收益$\vec{\Pi}$代替$\tilde{R}$</font>)：
$$\vec{w}_M = \frac{1}{\lambda} \Sigma^{-1} \vec{\Pi} \\
\vec{\Pi} = \lambda \Sigma \vec{w}_M
$$

风险厌恶因子

$$\vec{w}^{T} \vec{\Pi} = \lambda \vec{w}^{T} \Sigma \vec{w}_M = \lambda \sigma_M^2$$

$$\lambda = \frac{\vec{w}^{T} \vec{\Pi}}{\sigma_M^2} = \frac{1}{\sigma_M} S_M$$

夏普比率
$$S_M = \frac{\vec{w}^{T} \vec{\Pi}}{\sigma_M} $$

在模型中，夏普比例取0.5

假设$$\Sigma_{\Pi} = \tau \Sigma$$

得到先验概率分布
$$P(E) \sim N(\Pi, \tau \Sigma)$$

参数$\tau$

通常$\tau$接近于0，取值位于0.01到0.05之间
如果估计长度为T的时间序列的历史数据，取 $\tau \approx T^{-1}$

**Step 2: Inputing the views**

- Relative view：用资产之间的收益差衡量
- Absolute view：用资产的绝对收益衡量

$$P(I|E) \sim N(Q, \Omega)$$

$Q$是收益率向量
$\Omega$是置信度协方差矩阵

确定协方差矩阵$\Omega$
$$ \Omega := Diag(P(\tau \Sigma) P^T)$$

Diag是对角化函数

**Step 3: Combining to get the posterior distribution**

$$P(E|I) \sim
N([(\tau \Sigma)^{-1} + P^T \Omega^{-1} P]^{-1}[(\tau \Sigma)^{-1} \Pi + P^T \Omega^{-1} Q],
[(\tau \Sigma)^{-1} + P^T \Omega^{-1} P]^{-1})
$$

$$\hat{R}_I :=
\mathbb{E}[\tilde{R}|I] = [(\tau \Sigma)^{-1} + P^T \Omega^{-1} P]^{-1}[(\tau \Sigma)^{-1} \Pi + P^T \Omega^{-1} Q]
$$

**Step 4: Asset allocation**

$$\max_{\vec{w}} [r + w^T \hat{R}_I] - \frac{\lambda}w^T \Sigma w$$

求解得到
$$w^* = \frac{1}{\lambda} \Sigma^{-1} \hat{R}_I$$

In [6]:
# Step 1 计算先验概率P(E)

# 计算超额收益

# 夏普比率（模型设置夏普比率为0.5）
sr = 0.5
# 市场组合的权重
wm = np.array([0.05, 0.40, 0.45, 0.10, ]).reshape(4,1)
# 市场组合的标准差
sm = np.sqrt(np.matmul(np.matmul(wm.T, Cov), wm))
# 风险厌恶因子
lam = sr / sm
# 超额收益(Pi)
pi = lam.item(0, 0) * np.matmul(Cov, wm)

# 计算P(E)

T = 120

tau = 1 / T


#P(E)服从正态分布，均值为pi，方差为协方差矩阵 tau * Cov

# Step 2 Inputting the views 计算条件概率P(I|E)

P = np.array([[-1, 0, 1, 0, ], [0, 1, 0, 0], ])
Q = np.array([0.10, 0.03, ]).reshape(2, 1)

omega = np.matmul(np.matmul(P, tau * Cov), P.T)
omega = np.array(omega)

def diag(s) :
    for i in range(len(s)) :
        for j in range(len(s[i])) :
            if (i != j) :
                s[i][j] = 0

diag(omega)

# step 3 计算后延概率P(E|I)

tau_Cov_reverse = (tau * Cov).I
tmp1 = np.matmul(P.T, np.matrix(omega).I)
tmp2 = (tau_Cov_reverse + np.matmul(tmp1, P)).I

RI = np.matmul(tmp2, np.matmul(tau_Cov_reverse, pi) + np.matmul(tmp1, Q))
RI_std = tmp2

# step 4 资产配置

for lam in [ 0.1, 1, 2.24, 6, ] :
    wm = np.matmul(Cov_reverse, RI) / lam
    print(lam)
    print(wm)

0.1
[[2.19952517]
 [3.71924492]
 [8.98500411]
 [2.23690586]]
1
[[0.21995252]
 [0.37192449]
 [0.89850041]
 [0.22369059]]
2.24
[[0.09819309]
 [0.16603772]
 [0.40111625]
 [0.09986187]]
6
[[0.03665875]
 [0.06198742]
 [0.14975007]
 [0.03728176]]
