## 带等式约束的优化问题

### 给定风险，求解风险最小的组合权重

**符号**

收益的期望值
$$ \vec{\mu} = \left( \begin{matrix} \mu _1 \\ \vdots \\ \mu _i \\ \vdots \\ \mu _n \\ \end{matrix} \right) $$

收益的协方差矩阵
$$
\vec{\Sigma} = \left(
\begin{matrix}
\sigma_1^2 & \rho_{12} \sigma_1 \sigma_2 & \cdots & \rho_{1n} \sigma_1 \sigma_n \\
\rho_{21} \sigma_2 \sigma_1 & \sigma_2^2 & \cdots & \rho_{2n} \sigma_2 \sigma_n \\
\vdots & \vdots & \ddots & \vdots \\
\rho_{n1} \sigma_2 \sigma_n & \rho_{n2} \sigma_n \sigma_2 & \cdots & \sigma_n^2 \\
\end{matrix}
\right)
$$

资产权重
$$ \vec{w} = \left( \begin{matrix} w _1 \\ \vdots \\ w _i \\ \vdots \\ w _n \\ \end{matrix} \right) $$

组合收益的期望值 $\mu_\pi = \vec{\mu} ^ T \vec{w}$

组合收益的方差 $\sigma_\pi ^2 = \vec{w}^T \vec{\Sigma} \vec{w}$


**分解协方差矩阵**

标准差向量
$$ \vec{\sigma} = \left( \begin{matrix} \sigma _1 \\ \vdots \\ \sigma _i \\ \vdots \\ \sigma _n \\ \end{matrix} \right) $$

标准差对角阵

$$
\vec{S} = \vec{D}(\sigma) = \left(
\begin{matrix}
\sigma_1 & 0 & \cdots & 0 \\
0 & \sigma_2 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & \sigma_n \\
\end{matrix}
\right)
$$

相关性矩阵
$$
\vec{R} = \left(
\begin{matrix}
1 & \rho_{12} & \cdots & \rho_{1n} \\
\rho_{21} & 1 & \cdots & \rho_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
\rho_{n1} & \rho_{n2} & \cdots & 1 \\
\end{matrix}
\right)
$$

协方差矩阵
$$
\vec{\Sigma} = \vec{SRS} = \left(
\begin{matrix}
\sigma_1^2 & \rho_{12} \sigma_1 \sigma_2 & \cdots & \rho_{1n} \sigma_1 \sigma_n \\
\rho_{21} \sigma_2 \sigma_1 & \sigma_2^2 & \cdots & \rho_{2n} \sigma_2 \sigma_n \\
\vdots & \vdots & \ddots & \vdots \\
\rho_{n1} \sigma_2 \sigma_n & \rho_{n2} \sigma_n \sigma_2 & \cdots & \sigma_n^2 \\
\end{matrix}
\right)
$$

**拉格朗日方法**

等式的优化问题的一般形式如下：

$$\begin{aligned}
\min_{x_1, \cdots, x_n} f(x_1,\cdots, x_n)
\end{aligned}$$

subject to :

$$\begin{aligned}
& g_1(x_1,\cdots, x_n) & = & \ b_1 \\
& & \vdots \\
& g_m(x_1,\cdots, x_n) & = & \ b_m \\
\end{aligned}$$

使用拉格朗日方法构造无约束条件的优化形式：

$$L(\vec{x}, \vec{\lambda}) = f(\vec{x}) + \sum_{j=1}^{m} \lambda_j (g_j(\vec{x})-b_j)$$


**要求解的问题**：在给定回报的情况下，最小化组合风险

目标函数$\begin{aligned} \min_{\vec{w}} = \frac{1}{2} \sigma_{\pi}^2 = \frac{1}{2} \vec{w}^T \vec{\Sigma} \vec{w} \end{aligned}$

约束条件
- 目标收益：$\mu_{\pi} = \vec{\mu}^T \vec{w} = \vec{w}^T \vec{\mu} = m$
- 权重和为1：$\vec{1}^T \vec{w} = \vec{w}^T \vec{1} = 1$

使用拉格朗日方法构造无约束条件的优化问题：
$$
L(\vec{w}, \lambda, \gamma) = \frac{1}{2} \vec{w}^T \vec{\Sigma} \vec{w} + \lambda(m - \vec{w}^T \mu) + \gamma(1 - \vec{w}^T \vec{1})
$$

求解得到$\vec{w}^* = \vec{\Sigma}^{-1} (\lambda \vec{\mu} + \gamma \vec{1})$，其中，

$\left\{\begin{aligned}
\lambda &= \frac{Am-B}{AC-B^2} \\
\gamma &= \frac{C-Bm}{AC-B^2} \\
\end{aligned}\right.$

$\left\{\begin{aligned}
A &= \vec{1}^T \vec{\Sigma}^{-1} \vec{1} \\
B &= \vec{1}^T \vec{\Sigma}^{-1} \vec{\mu} = \vec{\mu}^T \vec{\Sigma}^{-1} \vec{1} \\
C &= \vec{\mu}^T \vec{\Sigma}^{-1} \vec{\mu} \\
\end{aligned}\right.$

In [43]:
import numpy as np

# 单位向量
unit = np.array([1.0, 1.0, 1.0, 1.0, ]).reshape(4, 1)

# 收益均值
u = np.array([0.05, 0.07, 0.15, 0.27, ]).reshape(4, 1)
# 收益方差
s = np.array([0.07, 0.12, 0.30, 0.60, ]).reshape(4, 1)
# 相关性矩阵
R = np.array([[1, 0.8, 0.5, 0.4, ],
             [0.8, 1, 0.7, 0.5, ],
             [0.5, 0.7, 1, 0.8, ],
             [0.4, 0.5, 0.8, 1, ], ])


In [44]:
# 目标收益
m = 0.1

print('====================')
print('params')
print()
print('mean of returns :')
print(u)
print()
print('standard deviation of returs :')
print(s)
print()
print('correlation matrix :')
print(R)
print()
print('target retusn :')
print(u_p)
print()
print('====================')

# 向量变为对角阵
S = np.diag(s.reshape(4))
# 协方差矩阵
Cov = np.matmul(np.matmul(S, R), S)
# 协方差矩阵的逆矩阵
Cov = np.matrix(Cov)
Cov_reverse = Cov.I

# 三个中间变量
A = np.matmul(np.matmul(unit.T, Cov_reverse), unit).item(0, 0)
B = np.matmul(np.matmul(u.T, Cov_reverse), unit).item(0, 0)
C = np.matmul(np.matmul(u.T, Cov_reverse), u).item(0, 0)

# 拉格朗日系数
lam = (A * m - B) / (A * C - B * B)
gam = (C - B * m) / (A * C - B * B)

# 权重w
w = np.matmul(Cov_reverse, lam * u + gam * unit)

print('++++++++++++++++++++')
print('standard deviation matrix')
print(S)
print()
print('covariance matrix')
print(Cov)
print()
print('inverse of covariance matrix')
print(Cov_reverse)
print()
print('A={}, B={}, C={}'.format(A, B, C))
print()
print('lambda={}, gamma={}'.format(lam, gam))
print()
print('weights')
print(w)
print()
print('++++++++++++++++++++')

params

mean of returns :
[[0.05]
 [0.07]
 [0.15]
 [0.27]]

standard deviation of returs :
[[0.07]
 [0.12]
 [0.3 ]
 [0.6 ]]

correlation matrix :
[[1.  0.8 0.5 0.4]
 [0.8 1.  0.7 0.5]
 [0.5 0.7 1.  0.8]
 [0.4 0.5 0.8 1. ]]

target retusn :
0.1

++++++++++++++++++++
standard deviation matrix
[[0.07 0.   0.   0.  ]
 [0.   0.12 0.   0.  ]
 [0.   0.   0.3  0.  ]
 [0.   0.   0.   0.6 ]]

covariance matrix
[[0.0049  0.00672 0.0105  0.0168 ]
 [0.00672 0.0144  0.0252  0.036  ]
 [0.0105  0.0252  0.09    0.144  ]
 [0.0168  0.036   0.144   0.36   ]]

inverse of covariance matrix
[[ 591.54096421 -310.55900621   34.50655625  -10.35196687]
 [-310.55900621  301.93236715  -64.41223833   10.06441224]
 [  34.50655625  -64.41223833   48.30917874  -14.49275362]
 [ -10.35196687   10.06441224  -14.49275362    8.05152979]]

A=239.3440467974628, B=9.6184560780834, C=0.5502809819580001

lambda=0.365279369427286, gamma=-0.010501299717695733

weights
[[0.52841211]
 [0.17288808]
 [0.15976434]
 [0.13893547]]

++++

### 最小方差组合

去掉约束条件1，即不给定期望收益

求解得到

最小方差组合的收益$m_g = \frac{B}{A}$

权重 $\begin{aligned} w_g = \frac{\vec{\Sigma}^{-1} \vec{1}}{A} \end{aligned}$

方差 $\begin{aligned} \sigma_g^2 = \frac{1}{A} \end{aligned}$

In [48]:
wg = np.matmul(Cov_reverse, unit) / A
mg = B/A
sg = np.sqrt(1/A)

print('weights')
print(wg)
print()

print('return')
print(mg)
print()

print('standard deviation')
print(sg)
print()


weights
[[ 1.27488672]
 [-0.26311273]
 [ 0.01633942]
 [-0.02811341]]

return
0.04018673623506796

standard deviation
0.06463811533136278



### 切线组合

优化问题变为：

目标函数$\begin{aligned} \min_{\vec{w}} = \frac{1}{2} \sigma_{\pi}^2 = \frac{1}{2} \vec{w}^T \vec{\Sigma} \vec{w} \end{aligned}$

约束条件
- $r + \vec{w}^T (\vec{\mu} - r \vec{1})= m$

求解得到 $$\vec{w}^* = \lambda \vec{\Sigma}^{-1}(\vec{\mu} - r \vec{1})$$

带入约束条件可求解出$$\lambda = \frac{m -r}{(\vec{\mu} - r \vec{1})^T \vec{\Sigma}^{-1} (\vec{\mu} - r \vec{1}) } $$, 

代入得到最终的 $$\vec{w}^* = \frac{ (m - r) \vec{\Sigma}^{-1} (\vec{\mu} - r \vec{1}) }{ (\vec{\mu} - r \vec{1})^T \vec{\Sigma}^{-1} (\vec{\mu} - r \vec{1}) }$$

In [55]:
r = 0.025
m = 0.1

t = u - r * unit

w = (m - r) * np.matmul(Cov_reverse, t) / np.matmul(np.matmul(t.T, Cov_reverse), t)

print(r)
print(m)
print(w)
print(1 - np.matmul(w.T, unit))

0.025
0.1
[[0.88735248]
 [0.08126325]
 [0.15484343]
 [0.12164862]]
[[-0.24510779]]


切线组合全部投资在风险资产上$$\vec{w_t} = \frac{\vec{\Sigma}^{-1}(\vec{\mu} - r \vec{1})}{B-Ar}$$

均值 $$m_t = \vec{w_t}^T = \frac{C-Br}{B-Ar}$$

方差 $$\sigma_t = \vec{w_t}^T \vec{\Sigma} \vec{w_t} = \frac{C-2rB +r^2 A}{(B-Ar)^2}$$

In [60]:
wt = np.matmul(Cov_reverse, u - r * unit) / (B - A * r)
mt = (C - B * r) / (B - A * r)
st = np.sqrt((C - 2 * B * r + A * r * r) / ((B - A * r) ** 2))
st

0.12873114050310236